### ISSUE TITLE
Please update with code from UN Vote screencast today(2021-03-23)

### ISSUE THREAD

**Issue by davidjayjackson** [dgrtwo/data-screencasts#17]
David,
Thanks, Another great screencast today.
Please push today's code up.

TX,
David

**Comment by dgrtwo** [comment]
I did right after the screencast 🙂 https://github.com/dgrtwo/data-screencasts/blob/master/2021_03_23_un_votes.Rmd

**Comment by davidjayjackson** [comment]
Thanks, I found it.
